# DeepSeek-V3 5B Configuration
# Total: ~5.0B parameters, ~1.5B active per token
# Hardware: 4-8 GPUs (A100/H100)

model:
  num_layers: 24
  vocab_size: 64000

  # MLA (Multi-head Latent Attention)
  mla:
    d_model: 2048
    d_latent: 512       # 1/4 of d_model
    num_heads: 32
    num_kv_heads: 32
    use_fp8_kv: false
    max_context_length: 16384
    use_flash_mla: true
    flash_mla_backend: "auto"
    use_rope: true
    rope_theta: 10000.0

  # MoE (Mixture of Experts)
  moe:
    num_experts: 16
    num_experts_per_token: 2
    expert_intermediate_size: 5120   # ~2.5x d_model
    num_shared_experts: 1
    shared_intermediate_size: 5120

    # Routing
    router_aux_loss_weight: 0.001
    router_temperature: 1.0
    router_noise_std: 0.1
    capacity_factor: 1.0

    # Load balancing
    use_aux_loss_free: false
    balance_loss_type: "entropy"

    # DeepEP
    use_deep_ep: false
    deep_ep_fp8: false
    deep_ep_async: false

  # Normalization
  norm_type: "rmsnorm"
  norm_eps: 1.0e-6

  # Embeddings
  tie_word_embeddings: false

  # Initialization
  init_method_std: 0.015

# Parallelism
parallel:
  tensor_parallel_size: 2
  pipeline_parallel_size: 1
  expert_parallel_size: 1
  data_parallel_size: -1

  zero_stage: 1
  zero_offload: false

  overlap_grad_reduce: true
  overlap_param_gather: true

# Training
training:
  # Batch settings
  global_batch_size: 512
  micro_batch_size: 2
  seq_length: 2048

  # Chinchilla-optimal scaling (REQ-T2P-1, REQ-T2P-2)
  # 5B model: ~1.79B active params → 35.8B tokens @20 T/P, 46.6B @26 T/P
  # Tokens/step: 512 × 2048 = 1,048,576
  # Required steps: 35.8B / 1.05M ≈ 34,133 steps
  tokens_per_parameter_ratio: 20.0  # Conservative Chinchilla optimum
  total_training_tokens: 35800000000  # 35.8B tokens (1.79B × 20)

  # Optimization
  learning_rate: 2.5e-4
  min_learning_rate: 2.5e-5
  lr_warmup_steps: 1500
  lr_decay_style: "cosine"
  weight_decay: 0.1
  grad_clip: 1.0

  # Mixed precision
  use_fp16: false
  use_bf16: true
  use_fp8: false

  # Multi-token prediction
  use_mtp: false

  # Schedule
  train_steps: 34133  # Updated for Chinchilla compliance
  eval_interval: 1000
  save_interval: 5000
  log_interval: 10

  # Optimizer
  optimizer: "adamw"
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-8

# Data
data:
  train_data_path: "/path/to/train_data"
  val_data_path: "/path/to/val_data"
  num_workers: 4
  prefetch_factor: 2

# Checkpointing
checkpoint:
  save_dir: "./checkpoints_5b"
  keep_last_n: 5
  save_optimizer_states: true

# Logging
logging:
  output_dir: "./outputs_5b"
  use_wandb: true
  wandb_project: "deepseek-v3-5b"
  wandb_entity: null
  log_level: "INFO"
