# DeepSeek-V3 15B Configuration
# Total: ~15B parameters, ~4.5B active per token
# Hardware: 16-24 GPUs (A100/H100)

model:
  num_layers: 40
  vocab_size: 100000

  # MLA (Multi-head Latent Attention)
  mla:
    d_model: 3584
    d_latent: 896       # 1/4 of d_model
    num_heads: 56
    num_kv_heads: 56
    use_fp8_kv: true
    max_context_length: 65536
    use_flash_mla: true
    flash_mla_backend: "auto"
    use_rope: true
    rope_theta: 10000.0

  # MoE (Mixture of Experts)
  moe:
    num_experts: 64
    num_experts_per_token: 4
    expert_intermediate_size: 10240  # ~2.86x d_model
    num_shared_experts: 2
    shared_intermediate_size: 10240

    # Routing
    router_aux_loss_weight: 0.0
    router_temperature: 1.0
    router_noise_std: 0.1
    capacity_factor: 1.0

    # Load balancing
    use_aux_loss_free: true
    balance_loss_type: "entropy"

    # DeepEP
    use_deep_ep: true
    deep_ep_fp8: true
    deep_ep_async: true

  # Normalization
  norm_type: "rmsnorm"
  norm_eps: 1.0e-6

  # Embeddings
  tie_word_embeddings: false

  # Initialization
  init_method_std: 0.010

# Parallelism
parallel:
  tensor_parallel_size: 4
  pipeline_parallel_size: 2
  expert_parallel_size: 2
  data_parallel_size: -1

  zero_stage: 1
  zero_offload: false

  overlap_grad_reduce: true
  overlap_param_gather: true

# Training
training:
  # Batch settings
  global_batch_size: 2048
  micro_batch_size: 1
  seq_length: 4096

  # Chinchilla-optimal scaling (REQ-T2P-1, REQ-T2P-2)
  # 15B model: ~15.81B active params → 316.2B tokens @20 T/P, 411.0B @26 T/P
  # Tokens/step: 2048 × 4096 = 8,388,608
  # Required steps: 316.2B / 8.39M ≈ 37,691 steps
  tokens_per_parameter_ratio: 20.0  # Conservative Chinchilla optimum
  total_training_tokens: 316200000000  # 316.2B tokens (15.81B × 20)

  # Optimization
  learning_rate: 1.8e-4
  min_learning_rate: 1.8e-5
  lr_warmup_steps: 2000
  lr_decay_style: "cosine"
  weight_decay: 0.1
  grad_clip: 1.0

  # Mixed precision
  use_fp16: false
  use_bf16: true
  use_fp8: true

  # Multi-token prediction
  use_mtp: true
  num_predict_tokens: 2

  # Schedule
  train_steps: 37691  # Updated for Chinchilla compliance
  eval_interval: 1000
  save_interval: 5000
  log_interval: 10

  # Optimizer
  optimizer: "adamw"
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-8

# Data
data:
  train_data_path: "/path/to/train_data"
  val_data_path: "/path/to/val_data"
  num_workers: 4
  prefetch_factor: 2

# Checkpointing
checkpoint:
  save_dir: "./checkpoints_15b"
  keep_last_n: 5
  save_optimizer_states: true

# Logging
logging:
  output_dir: "./outputs_15b"
  use_wandb: true
  wandb_project: "deepseek-v3-15b"
  wandb_entity: null
  log_level: "INFO"
