# DeepSeek-V3 1B Configuration
# Total: ~1.0B parameters, ~300M active per token
# Hardware: 1-2 GPUs (A100/H100)

model:
  num_layers: 16
  vocab_size: 32000

  # MLA (Multi-head Latent Attention)
  mla:
    d_model: 1024
    d_latent: 256       # 1/4 of d_model
    num_heads: 16
    num_kv_heads: 16
    use_fp8_kv: false
    max_context_length: 8192
    use_flash_mla: true
    flash_mla_backend: "auto"
    use_rope: true
    rope_theta: 10000.0

  # MoE (Mixture of Experts)
  moe:
    num_experts: 8
    num_experts_per_token: 2
    expert_intermediate_size: 2048   # ~2x d_model
    num_shared_experts: 0
    shared_intermediate_size: 0

    # Routing
    router_aux_loss_weight: 0.001
    router_temperature: 1.0
    router_noise_std: 0.1
    capacity_factor: 1.0

    # Load balancing
    use_aux_loss_free: false
    balance_loss_type: "entropy"

    # DeepEP
    use_deep_ep: false  # Not needed for small scale
    deep_ep_fp8: false
    deep_ep_async: false

  # Normalization
  norm_type: "rmsnorm"
  norm_eps: 1.0e-6

  # Embeddings
  tie_word_embeddings: false

  # Initialization
  init_method_std: 0.02

# Parallelism
parallel:
  tensor_parallel_size: 1
  pipeline_parallel_size: 1
  expert_parallel_size: 1
  data_parallel_size: -1  # Auto

  zero_stage: 1
  zero_offload: false

  overlap_grad_reduce: true
  overlap_param_gather: true

# Training
training:
  # Batch settings
  global_batch_size: 256
  micro_batch_size: 4
  seq_length: 2048

  # Chinchilla-optimal scaling (REQ-T2P-1, REQ-T2P-2)
  # 1B model: ~300M active params → 6B tokens @20 T/P, 7.8B @26 T/P
  # Tokens/step: 256 × 2048 = 524,288
  # Required steps: 6B / 524K ≈ 11,444 steps
  tokens_per_parameter_ratio: 20.0  # Conservative Chinchilla optimum
  total_training_tokens: 6000000000  # 6B tokens (300M × 20)

  # Optimization
  learning_rate: 3.0e-4
  min_learning_rate: 3.0e-5
  lr_warmup_steps: 1000
  lr_decay_style: "cosine"
  weight_decay: 0.1
  grad_clip: 1.0

  # Mixed precision
  use_fp16: false
  use_bf16: true
  use_fp8: false

  # Multi-token prediction
  use_mtp: false

  # Schedule
  train_steps: 11444  # Updated for Chinchilla compliance
  eval_interval: 1000
  save_interval: 5000
  log_interval: 10

  # Optimizer
  optimizer: "adamw"
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-8

# Data
data:
  train_data_path: "/path/to/train_data"
  val_data_path: "/path/to/val_data"
  num_workers: 2
  prefetch_factor: 2

# Checkpointing
checkpoint:
  save_dir: "./checkpoints_1b"
  keep_last_n: 5
  save_optimizer_states: true

# Logging
logging:
  output_dir: "./outputs_1b"
  use_wandb: false
  wandb_project: "deepseek-v3-1b"
  wandb_entity: null
  log_level: "INFO"
