# DeepSeek-V3 20B Configuration
# Total: ~20B parameters, ~6B active per token
# Hardware: 24-32 GPUs (A100/H100)

model:
  num_layers: 48
  vocab_size: 128000

  # MLA (Multi-head Latent Attention)
  mla:
    d_model: 4096
    d_latent: 1024      # 1/4 of d_model
    num_heads: 64
    num_kv_heads: 64
    use_fp8_kv: true
    max_context_length: 65536
    use_flash_mla: true
    flash_mla_backend: "auto"
    use_rope: true
    rope_theta: 10000.0

  # MoE (Mixture of Experts)
  moe:
    num_experts: 96
    num_experts_per_token: 6
    expert_intermediate_size: 11264  # ~2.75x d_model
    num_shared_experts: 2
    shared_intermediate_size: 11264

    # Routing
    router_aux_loss_weight: 0.0
    router_temperature: 1.0
    router_noise_std: 0.1
    capacity_factor: 1.0

    # Load balancing
    use_aux_loss_free: true
    balance_loss_type: "entropy"

    # DeepEP
    use_deep_ep: true
    deep_ep_fp8: true
    deep_ep_async: true

  # Normalization
  norm_type: "rmsnorm"
  norm_eps: 1.0e-6

  # Embeddings
  tie_word_embeddings: false

  # Initialization
  init_method_std: 0.008

# Parallelism
parallel:
  tensor_parallel_size: 4
  pipeline_parallel_size: 2
  expert_parallel_size: 2
  data_parallel_size: -1

  zero_stage: 1
  zero_offload: false

  overlap_grad_reduce: true
  overlap_param_gather: true

# Training
training:
  # Batch settings
  global_batch_size: 3072
  micro_batch_size: 1
  seq_length: 4096

  # Chinchilla-optimal scaling (REQ-T2P-1, REQ-T2P-2)
  # 20B model: ~32.74B active params → 654.7B tokens @20 T/P, 851.2B @26 T/P
  # Tokens/step: 3072 × 4096 = 12,582,912
  # Required steps: 654.7B / 12.58M ≈ 52,033 steps
  tokens_per_parameter_ratio: 20.0  # Conservative Chinchilla optimum
  total_training_tokens: 654700000000  # 654.7B tokens (32.74B × 20)

  # Optimization
  learning_rate: 1.8e-4
  min_learning_rate: 1.8e-5
  lr_warmup_steps: 2000
  lr_decay_style: "cosine"
  weight_decay: 0.1
  grad_clip: 1.0

  # Mixed precision
  use_fp16: false
  use_bf16: true
  use_fp8: true

  # Multi-token prediction
  use_mtp: true
  num_predict_tokens: 2

  # Schedule
  train_steps: 52033  # Updated for Chinchilla compliance
  eval_interval: 1000
  save_interval: 5000
  log_interval: 10

  # Optimizer
  optimizer: "adamw"
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-8

# Data
data:
  train_data_path: "/path/to/train_data"
  val_data_path: "/path/to/val_data"
  num_workers: 4
  prefetch_factor: 2

# Checkpointing
checkpoint:
  save_dir: "./checkpoints_20b"
  keep_last_n: 5
  save_optimizer_states: true

# Logging
logging:
  output_dir: "./outputs_20b"
  use_wandb: true
  wandb_project: "deepseek-v3-20b"
  wandb_entity: null
  log_level: "INFO"
